(ns utterlyidle.media-types)

(def wildcard "*/*")
(def application-xml "application/xml")
(def application-atom-xml "application/atom+xml")
(def application-xhtml-xml "application/xhtml+xml")
(def application-svg-xml "application/svg+xml")
(def application-javascript "application/javascript")
(def application-json "application/json")
(def application-pdf "application/pdf")
(def application-form-urlencoded "application/x-www-form-urlencoded")
(def application-octet-stream "application/octet-stream")
(def application-ms-excel "application/vnd.ms-excel")
(def multipart-form-data "multipart/form-data")
(def text-plain "text/plain")
(def text-csv "text/csv")
(def text-xml "text/xml")
(def text-html "text/html")
(def text-css "text/css")
(def text-javascript "text/javascript")
(def text-cache-manifest "text/cache-manifest")
(def image-png "image/png")
(def image-gif "image/gif")
(def image-x-icon "image/x-icon")
(def image-jpeg "image/jpeg")
(def image-svg "image/svg+xml")